services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_NAME_CORPORATION: ${NEXT_PUBLIC_NAME_CORPORATION}
        NEXT_PUBLIC_LOGO_CORPORATION: ${NEXT_PUBLIC_LOGO_CORPORATION}
        BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL}
        DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"